# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiTermos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias_in_text', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wikigame',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termo', to='wikigame.WikiTermos'),
        ),
        migrations.AddField(
            model_name='wikigame',
            name='out_links_set',
            field=models.ManyToManyField(related_name='out_links', to='wikigame.WikiTermos', verbose_name='Out Links'),
        ),
    ]
