# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikigame', '0003_auto_20190204_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikigame',
            name='imagem',
            field=models.CharField(default='', max_length=255),
        ),
    ]
