# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='nomeDaCrianca',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
