# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20171201_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='justificativa',
            field=models.CharField(max_length=25555),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='projetoDeLei',
            field=models.CharField(max_length=25555),
        ),
    ]
