# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-04 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_auto_20171204_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='justificativa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='projetoDeLei',
            field=models.TextField(),
        ),
    ]
