# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_auto_20171204_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
