# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-07-16 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_auto_20180704_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='cep',
        ),
        migrations.AddField(
            model_name='projeto',
            name='como_chegou',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='parentesco',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
