# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-07-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_remove_projeto_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='como_chegou',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='parentesco',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='responsavel',
            field=models.TextField(null=True),
        ),
    ]
