# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SaibaMais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='etapa',
            name='opcao1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcao1', to='trivia.Opcao', verbose_name='Opção 1'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='opcao2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcao2', to='trivia.Opcao', verbose_name='Opção 2'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='opcao3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcao3', to='trivia.Opcao', verbose_name='Opção 3'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='opcao4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcao4', to='trivia.Opcao', verbose_name='Opção 4'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='pergunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='trivia.Pergunta'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='resposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='trivia.Opcao'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='saiba_mais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.SaibaMais', verbose_name='Saiba mais'),
        ),
    ]
