# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='opcao1',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='opcao2',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='opcao3',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='opcao4',
        ),
        migrations.AddField(
            model_name='etapa',
            name='opcoes',
            field=models.ManyToManyField(null=True, related_name='opcoes', to='trivia.Opcao', verbose_name='Opções'),
        ),
    ]
