# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20180208_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='opcoes',
        ),
        migrations.AddField(
            model_name='etapa',
            name='opcao_set',
            field=models.ManyToManyField(related_name='opcoes', to='trivia.Opcao', verbose_name='Opções'),
        ),
        migrations.AddField(
            model_name='trivia',
            name='etapa_set',
            field=models.ManyToManyField(related_name='etapa', to='trivia.Etapa', verbose_name='Etapas'),
        ),
    ]
