# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-06 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_auto_20180209_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saibamais',
            options={'verbose_name_plural': 'Saiba Mais'},
        ),
    ]
