# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-06 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_auto_20180306_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=1024),
        ),
    ]
