# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20180306_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.TextField(),
        ),
    ]
