# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-06 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0012_auto_20180306_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='texto2',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='texto3',
        ),
    ]
