# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-13 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0013_auto_20180306_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'verbose_name_plural': 'Opções'},
        ),
    ]
